<?php


namespace Wuxuejian\DcatVr\Http\Resources;


use Illuminate\Http\Resources\Json\JsonResource;

class SceneResource extends JsonResource
{

    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'vr_id' => $this->vr_id,
            'name' => $this->name,
            'description' =>$this->description,
            'scene_file' => $this->scene_file,
            'cover' => $this->cover,
            'scene_type' => $this->scene_type,
            'init_tilt' => $this->init_tilt,
            'init_pan' => $this->init_pan,
            'init_fov' => $this->fov,
            'scene_format' => $this->scene_format,
            'is_loop' => $this->is_loop,
            'status' => $this->status,
            'updated_at' => $this->updated_at->format($this->getDateFormat()),
            'vr' => $this->whenLoaded('vr'),
        ];
    }

    public function with($request)
    {
        $this->with = [
            'meta'=> [
                'status' => [1=>'正常',0=>'关闭']
            ]
        ];
        return parent::with($request); // TODO: Change the autogenerated stub
    }
}
